---
title: "changeOD"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{changeOD}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE,
  echo = FALSE
)
```

```{r setup}
library(collapse)
```

# Datasets

## 2011 Origin-Destination data

```{r, eval=FALSE}
od = pct::get_od()
names(od)
#  [1] "geo_code1"     "geo_code2"     "all"           "from_home"
#  [5] "light_rail"    "train"         "bus"           "taxi"
#  [9] "motorbike"     "car_driver"    "car_passenger" "bicycle"
# [13] "foot"          "other"         "geo_name1"     "geo_name2"
# [17] "la_1"          "la_2"
# Remove unwanted variables with fselect:
od = od |>
  fselect(-la_1, -la_2, -geo_name1, -geo_name2, -all)
# Save as arrow file:
arrow::write_parquet(od, "od_2011.parquet")
# Upload to GitHub with piggyback:
piggyback::pb_upload("od_2011.parquet")
```

```{r}
od_2011 = arrow::read_parquet("od_2011.parquet")
```

```{r, eval=FALSE}

```

## 2021 Origin-Destination data

See the data at [WICID](https://wicid.ukdataservice.ac.uk/flowdata/cider/wicid/downloads.php) (requires login for data with mode).

```{r, eval=FALSE}
list.files(pattern = "zip")
od_2022_raw = readr::read_csv("ODWP15EW_MSOA_v1.zip")
names(od_2022_raw)
names(od_2022_raw)
#  [1] "Middle layer Super Output Areas code"
#  [2] "Middle layer Super Output Areas label"
#  [3] "MSOA of workplace code"
#  [4] "MSOA of workplace label"
#  [5] "Method used to travel to workplace (12 categories) code"
#  [6] "Method used to travel to workplace (12 categories) label"
#  [7] "Sex (2 categories) code"
#  [8] "Sex (2 categories) label"
#  [9] "Age (E) (8 categories) code"
# [10] "Age (E) (8 categories) label"
# [11] "Place of work indicator (4 categories) code"
# [12] "Place of work indicator (4 categories) label"
# [13] "Count"
# Pivot wider keeping only MSOA code (geo_code new name) and mode of travel (mode new name):
od_2022_by_mode = od_2022_raw |>
  pivot(
    id = c(
      "Middle layer Super Output Areas code",
      "MSOA of workplace code"
    ),
    values = "Count",
    names = "Method used to travel to workplace (12 categories) label",
    how = "wider"
  )
names(od_2022_by_mode)
#  [1] "Middle layer Super Output Areas code"
#  [2] "MSOA of workplace code"
#  [3] "Not in employment or aged 15 years and under"
#  [4] "Underground, metro, light rail, tram"
#  [5] "Train"
#  [6] "Bus, minibus or coach"
#  [7] "Taxi"
#  [8] "Driving a car or van"
#  [9] "Passenger in a car or van"
# [10] "Bicycle"
# [11] "On foot"
# [12] "Other method of travel to work"
# [13] "Work mainly at or from home"
# [14] "Motorcycle, scooter or moped"

# Change names to match 2011 dataset:
names(od_2022_by_mode) = c(
  "geo_code1",
  "geo_code2",
  "not_in_employment_or_aged_15_years_and_under",
  "light_rail",
  "train",
  "bus",
  "taxi",
  "car_driver",
  "car_passenger",
  "bicycle", # 10
  "foot",
  "other",
  "from_home",
  "motorbike"
)
ncol(od_2022_by_mode)
ncol(od_2011)
waldo::compare(names(od_2022_by_mode), names(od_2011))
od_2021 = od_2022_by_mode[names(od_2011)]
# Set all NAs to 0:
od_2021[is.na(od_2021)] = 0
# Compare working from home numbers:
sum(od_2011$from_home)
sum(od_2021$from_home)
# Save as arrow file:
arrow::write_parquet(od_2021, "od_2021.parquet")
```

```{r}
od_2021 = arrow::read_parquet("od_2021.parquet")
```

```{r}
# Check the summaries are similar:
cor(
  colMeans(od_2011[-(1:2)], na.rm = TRUE),
  colMeans(od_2021[-(1:2)], na.rm = TRUE)
)
# [1] 0.99027
# Save as combined dataset:
od_combined = rowbind(
  od_2011 |> fmutate(year = 2011),
  od_2021 |> fmutate(year = 2021)
)
# Save as arrow file:
arrow::write_parquet(od_combined, "od_combined.parquet")
```

# OD basics

Basic info on the 2011 and 2021 datasets are presented in the table below.

```{r}
od_combined = arrow::read_parquet("od_combined.parquet")
od_summary = data.frame(
  year = c(2011, 2021),
  n = c(nrow(od_2011), nrow(od_2021)),
  sum = c(sum(od_2011[-(1:2)]), sum(od_2021[-(1:2)]))
)
# od_summary |>
#   knitr::kable()

```

| year|       n|      sum|
|----:|-------:|--------:|
| 2011| 2402201| 26681568|
| 2021| 1851505|  4583443|